Commit

diff --git a/.github/workflows/Deployment.yml b/.github/workflows/Deployment.yml
--- a/.github/workflows/Deployment.yml
+++ b/.github/workflows/Deployment.yml
@@ -18,8 +18,17 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.8'  # Specify your Python version here
+
+      - name: Install dependencies
+        run: |
+          pip install -r requirements.txt  # Install your project's dependencies
+
       # Run Bandit to check Python code security issues
       - name: Run Bandit security check
         run: |
           pip install bandit
-          bandit -r ./book_catalog/app
+          bandit -r ./book_catalog/app || exit 1  # Fail the job if Bandit finds issues
